apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
stringData:
  {{- with (index .Values.airflow.airflow.users 0)}}
  airflow_user: {{ .username }}      # TODO
  airflow_password: {{ .password }}  # TODO
  {{- end }}
