apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
stringData:
  endpoint: ""    # FILL IN; https required (https:// prefix should be ommited)
  access_key: ""  # FILL IN
  secret_key: ""  # FILL IN