apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
stringData:
  # FILL IN if using other service than AWS S3; endpoint must use https (https:// prefix should be omitted in this value)
  # e.g. for https://example.com the value for endpoint should be "example.com"
  endpoint: ""
  access_key: ""  # FILL IN (required)
  secret_key: ""  # FILL IN (required)