apiVersion: v1
kind: Service
metadata:
  name: hmse-k8s-frontend-service
spec:
  selector:
    app: hmse-k8s-frontend
  ports:
  - name: hmse-k8s-frontend
    protocol: TCP
    port: {{ .Values.httpPort }}
    targetPort: 8080