kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.simulationPvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.simulationPvc.size }}